version: "3"
services:
  rabbitmq:
    image: yeseong31/spring-chat-repo
    container_name: rabbitmq_chat
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}