version: "3"
services:
  database:
    container_name: database
    image: mariadb
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    restart: always
    networks:
      spring-chat-net:
        ipv4_address: 172.27.0.2

  rabbitmq:
    image: yeseong31/spring-rabbitmq
    container_name: rabbitmq_chat
    hostname: rabbitmq_container
    ports:
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
      - "15692:15692"
      - "61613:61613"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: always
    networks:
      spring-chat-net:
        ipv4_address: 172.27.0.4

  mongodb:
    image: mongo
    container_name: mongo_chat
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    networks:
      spring-chat-net:
        ipv4_address: 172.27.0.3

  application:
    image: yeseong31/spring-chat-app
    container_name: spring_chat_app
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/${MARIADB_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - database
      - rabbitmq
      - mongodb
    restart: always
    networks:
      spring-chat-net:
        ipv4_address: 172.27.0.5

networks:
  spring-chat-net:
    ipam:
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1