version: "3"
services:
  rabbitmq:
    image: rabbitmq_custom
    container_name: rabbitmq_chat
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: "username"
      RABBITMQ_DEFAULT_PASS: "password"